server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: test
environment: test
server:
  port: 4000
myCustomVarTree:
  welcomeMsg: Hello from test
---
spring:
  config:
    activate:
      on-profile: prod
environment: prod
server:
  port: 5000
myCustomVarTree:
  welcomeMsg: Hello from prod